server:
  port: 9000
spring:
  application:
    name: server
  main:
    banner-mode: off
  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    password: password
    url: jdbc:h2:file:./clients
  h2:
    console.enabled: true
  jpa:
    hibernate.ddl-auto: create-drop
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
  sql:
    init.mode: always